services:
  - type: web
    name: fastapi-app
    env: python
    repo: https://github.com/maher-jaber/api-chat-bot.git
    branch: main
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000